---
  title: "immune coculture analysis"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  flexdashboard::flex_dashboard:
  orientation: rows
vertical_layout: fill
editor_options: 
  chunk_output_type: inline
knit: (function(inputFile, encoding) {
  rmarkdown::render(input = inputFile,
                    encoding = encoding,
                    output_file = if (exists("user")){paste0(
                      xfun::sans_ext(inputFile), '_',user, "_", format(Sys.Date(), "%d%m%y"), '.html'
                    )} else {paste0(xfun::sans_ext(inputFile), '_',"Guest", "_", format(Sys.Date(), "%d%m%y"), '.html')},
                    output_dir = if (exists("data.path")) paste0(data.path, "/HTML_Reports") else NULL
  )
})
---
  
  
  
```{r load libraries, include=FALSE}

# clear global enviroment                          
rm(list = setdiff(ls(), c("data.path", "user")))
invisible({gc()})

# initiate timer
start.time <- proc.time()

# load packages
packages2load <- c("scMiko", "Seurat", "plyr",  "dplyr", "tidyr", "reshape2", 
                   "DT", "flexdashboard", "ggpmisc", "future", "foreach", "doParallel",
                   "AnnotationDbi", "org.Mm.eg.db", "org.Hs.eg.db", "fgsea", "ggplot2", "reactome.db",
                   "schex", "RColorBrewer", "cowplot")

# load packages
invisible(lapply(packages2load, library, character.only = TRUE))

```


```{r import data}

dir.path <- "C:/Users/n mikolajewicz/Dropbox/PDF Projects - JM/Data/scRNA-seq/01_sci-RNA-seq3_Hong_Kevin_Jason/NM_HH/GBM/Reboot/Data/01_CRISPR_screens/DEMO_MUS_screens/"

all.folders <- list.files(path = dir.path)

limma.list <- list()
for (i in 1:length(all.folders)){
  current.folder <- all.folders[i]
  limma.list[[current.folder]] <- read.delim(file = paste0(dir.path, current.folder, "/limma_results.txt"))
  colnames( limma.list[[current.folder]]) <- c("gene", "lfc", "n_genes", "direction", "pval", "fdr")
  limma.list[[current.folder]]$sample <- current.folder
}

df.limma <- dplyr::bind_rows(limma.list)
df.limma$z <- scMiko::p2z(df.limma$fdr) * sign(df.limma$lfc)

```

```{r Gene Rank per Sample, fig.width=2, fig.height=5}

gr.plot <- function(dat, which.filter, which.val = "z", scale.lim = 13){
  
  if (which.val == "lfc"){
    dat$z <- dat$lfc
  } else if (which.val == "p"){
    dat$z <- dat$logp 
  }
  
  df.current <- dat %>%
    dplyr::filter(grepl(which.filter, sample)) %>%
    dplyr::mutate(gene.rank = rank(z, ties.method = "random"))
  
  df.current$type <- "Other"
  df.current$type[df.current$lfc > 0 & df.current$fdr < 0.05] <- "Suppressor"
  df.current$type[df.current$lfc < 0 & df.current$fdr < 0.05] <- "Sensitizer"
  
  
  stopifnot(nrow(df.current) < 20000)
  
  df.top <-  bind_rows(df.current %>% dplyr::top_n(10, z), df.current %>% dplyr::top_n(10, -z))

  point.size <- 1
  df.current %>%
    dplyr::arrange(-abs(z)) %>%
    ggplot((aes(x = gene.rank, y = z))) + 
    scattermore::geom_scattermore(aes(fill =type), color = "grey",pch=21, pointsize = point.size) + 
    geom_point(data = subset(df.current, type == 'Sensitizer') %>%  dplyr::arrange(abs(z)) , 
               aes(x = gene.rank, y = z, fill =type, fill = type,  size = abs(z)), color = "black",pch=21) + 
    geom_point(data = subset(df.current, type == 'Suppressor') %>%  dplyr::arrange(abs(z)) , 
               aes(x = gene.rank, y = z, type =type, fill = type, size = abs(z)), color = "black",pch=21) + 
    xlab("Gene Rank") + 
    ylab("Z (Limma)") + 
    geom_hline(yintercept = 0, linetype = "dashed") + 
    theme_classic() +
    scale_size(range = c(1,6)) +
    ggtitle("Gene Rank Differences") +
    ggrepel::geom_text_repel(data = df.top, aes(x = gene.rank, y = z, label = gene), max.overlaps = Inf) +
    scale_fill_manual(values = c("Other" = "#A9A9A9","Sensitizer" = "#0000FF" ,"Suppressor" =  "#FFFF00")) + 
    theme(legend.position = "none") + 
    coord_cartesian(ylim = c(-scale.lim, scale.lim))
  
}

which.val = "z"


df.limma$logp <- -log10(df.limma$fdr) * sign(df.limma$lfc)

p1 <- gr.plot(dat = df.limma, which.filter = "CT2A-OVA_Ctrl-T19_vs_CTL-T19", which.val = which.val ) +
  labs(title = "CT2A/CTL", subtitle = "T19")
p2 <- gr.plot(dat = df.limma, which.filter = "NK-T29", which.val = which.val) + 
  labs(title = "NK Cells", subtitle = "T29")
p3 <- gr.plot(dat = df.limma %>% dplyr::filter(sample %in% "MUS031_CT2A_Ctrl-T31_vs_J774-T31"), 
              which.filter = "J774-T31", which.val = which.val) + 
  labs(title = "J774 - macrophage", subtitle = "non-phagocyctic")

p4 <- gr.plot(dat = df.limma, which.filter = "Ctrl-T21_vs_RAW2647-T21", which.val = which.val) + 
  labs(title = "Raw 264.6 - T21", subtitle = "macrophage")
p5 <- gr.plot(dat = df.limma, which.filter = "CT2A-OVA-Ctrl-T21_vs_BV2-T21", which.val = which.val) + 
  labs(title = "BV2 - T21", subtitle = "microglia")
p6 <- gr.plot(dat = df.limma, which.filter = "Ctrl-T27_vs_J774-aCD29-T27", which.val = which.val) + 
  labs(title = "J774 - Microglia + aCD29", subtitle = "phagocyctic") # J7741-T9, J7741-T27


```

```{r save gene rank plots, fig.width=2*7, fig.height=5}

plt.combo <- cowplot::plot_grid(p5, p4, p3, p6, p1, p2,  nrow = 1)
plt.combo

# savePDF("rankPlots_coculture_screens_110623.pdf", plt.combo, fig.width=2*7, fig.height=5)
```





```{r}

```







